-- MySQL Script generated by MySQL Workbench
-- Sat Oct 18 16:22:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema burger_station
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `burger_station` ;

-- -----------------------------------------------------
-- Schema burger_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `burger_station` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `burger_station` ;

-- -----------------------------------------------------
-- Table `burger_station`.`_prisma_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`_prisma_migrations` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `burger_station`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`user` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burger_station`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`category` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_category_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `burger_station`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `burger_station`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`order` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `total` DOUBLE NOT NULL,
  `date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `orderReadyAt` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `burger_station`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`product` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `price` DOUBLE NOT NULL,
  `image` VARCHAR(191) NOT NULL,
  `categoryId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Product_categoryId_fkey` (`categoryId` ASC),
  CONSTRAINT `Product_categoryId_fkey`
    FOREIGN KEY (`categoryId`)
    REFERENCES `burger_station`.`category` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 120
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `burger_station`.`orderproducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`orderproducts` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`orderproducts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `orderId` INT(11) NOT NULL,
  `productId` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `OrderProducts_orderId_fkey` (`orderId` ASC),
  INDEX `OrderProducts_productId_fkey` (`productId` ASC),
  CONSTRAINT `OrderProducts_orderId_fkey`
    FOREIGN KEY (`orderId`)
    REFERENCES `burger_station`.`order` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `OrderProducts_productId_fkey`
    FOREIGN KEY (`productId`)
    REFERENCES `burger_station`.`product` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `burger_station`.`adiciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`adiciones` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`adiciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `precio` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `burger_station`.`orderproducts_has_adiciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burger_station`.`orderproducts_has_adiciones` ;

CREATE TABLE IF NOT EXISTS `burger_station`.`orderproducts_has_adiciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `orderproducts_id` INT(11) NOT NULL,
  `adiciones_id` INT NOT NULL,
  INDEX `fk_orderproducts_has_adiciones_adiciones1_idx` (`adiciones_id` ASC),
  INDEX `fk_orderproducts_has_adiciones_orderproducts1_idx` (`orderproducts_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_orderproducts_has_adiciones_orderproducts1`
    FOREIGN KEY (`orderproducts_id`)
    REFERENCES `burger_station`.`orderproducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderproducts_has_adiciones_adiciones1`
    FOREIGN KEY (`adiciones_id`)
    REFERENCES `burger_station`.`adiciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
